---
applications:
- name: latencyanalyzer
  memory: 512M
  instances: 1
  path: ../target/build/app.zip
  buildpack: java_buildpack
  env:
    INTERVAL: 10
    URL: http://latencyanalyzer.cf3.hybris.com/latencyanalyzer/ping
